name: badhaso_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  responsive_grid_list: ^1.4.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.1
  # Firebase dependencies
  firebase_auth: ^5.5.1
  dotted_border: ^2.1.0
  audioplayers: ^5.1.0
  confetti: ^0.7.0
  http: ^1.2.0
  path: ^1.8.3
  lottie: ^3.3.1
  cloud_firestore: ^5.6.5
  in_app_purchase: ^3.1.13
  purchases_flutter: ^8.7.1
  url_launcher: ^6.3.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/settings_icons/
    - assets/images/difficulty/
    - assets/icons/
    - assets/data/audio/
    - assets/data/audio/nonfiction/
    - assets/data/audio/egyptian/
    - assets/data/audio/egyptian/nonfiction/
    - assets/data/audio/jordanian/
    - assets/data/audio/jordanian/nonfiction/
    - assets/data/audio/moroccan/
    - assets/data/audio/moroccan/nonfiction/
    - assets/data/timestamps/
    - assets/svg/
    - assets/svg/play_button/
    - assets/lottie/
    - assets/stories_json/
    - assets/stories_json/msa/
    - assets/stories_json/egyptian/
    - assets/stories_json/jordanian/
    - assets/stories_json/moroccan/
    - assets/story_images/
    - assets/nonfiction_images/
    
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoBlack.ttf
          weight: 900
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
